server:
  port: 8080
  servlet:
    context-path: "/springboot-redis"
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    # 如果使用的jedis 则将lettuce改成jedis即可
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0
